repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
    -   id: ruff
    -   id: ruff-format
        args: ["--diff", "--config", "ruff.toml"]
-   repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.5.12
    hooks:
    -   id: tombi-format
        args: [ "--offline" ]
