name: Run checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Install pre-commit
        run: uv tool run pre-commit install
      - name: Run pre-commit
        run: uv tool run pre-commit run --all-files
      - name: Run unit tests
        run: uv run -m pytest
      - name: Check documentation building
        env:
          SPHINXOPTS: "-W"
        run: |
          uv pip install . && cd docs && uv run make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build/html'
          name: github-pages
